name: Python Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install libegl1-mesa-dev
          sudo apt-get install -y xvfb xorg-dev
          pip install .[dev]

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Set DISPLAY
        run: export DISPLAY=:99

      - name: Run tests
        run: pytest pymead/tests
