name: Python Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |  # libegl1 needed for Qt import
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install libegl1-mesa-dev
          sudo apt-get install -y xvfb xorg-dev
          sudo apt install libxkbcommon-x11-0
          sudo apt install libxcb-icccm4
          sudo apt install libxcb-image0
          sudo apt install libxcb-keysyms1
          sudo apt install libxcb-randr0
          sudo apt install libxcb-render-util0
          sudo apt install libxcb-xinerama0
          sudo apt install libxcb-xfixes0
          sudo apt install x11-utils
          sudo apt-get install libxcb-cursor0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          pip install .[dev]

      - name: Run tests
        run: pytest pymead/tests  # xvfb-run for headless X server (used in GUI tests)
