name: Standalone Executable Generator

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
#      - name: Install NuGet
#        run: |
#          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
#          Register-PackageSource -Name "NuGet" -Location "https://api.nuget.org/v3/index.json" -ProviderName NuGet
#          $sourceNugetExe = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
#          $targetNugetExe = "$rootPath\nuget.exe"
#          Invoke-WebRequest $sourceNugetExe -OutFile $targetNugetExe
#          Set-Alias nuget $targetNugetExe -Scope Global -Verbose
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: InnoSetup
        run: winget install --accept-package-agreements --accept-source-agreements --locale "en-US" innosetup
      - name: Install Pyinstaller
        run: pip install pyinstaller
      - name: Install pymead
        run: pip install .
      - name: Generate executable
        run: |
          cd install
          python -m install
