name: Standalone Executable Generator

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    env:
      DISPLAY: ':99.0'  # Environmental display variable used by X server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install .
      - name: Generate executable
        run: |
          cd ..
          echo %cd%
